### ISSUE TITLE
Bad problem with preparse and Matrix,  Craft 3.7

### ISSUE THREAD

**Issue by adrienne** [besteadfast/craft-preparse-field#76] opened 2021-07-31 00:38 UTC
@jalendport I'm not sure how to describe this one exactly, unfortunately. Basically, we have several Matrices on the page; one is referenced by the Preparse field (and the others are not).

For whatever reason, having the Preparse field in the entry at all (it is **not**, itself, part of a Matrix; it's a separate single field in the entry) means that the referenced Matrix comes … detached, basically, from the entry? Any new Matrix rows *in that field* will *save* to the database but they won't be *connected* to the actual entry. Matrix rows in other fields save just fine, however.

It's definitely a Preparse problem, because removing the field from the Entry Type completely fixes it.

I can hop on a call via Discord or Zoom and show someone the issue; it's definitely kind of weird to describe.

**Comment by adrienne** [comment] 2021-07-31 00:44
(It definitely worked in 3.6, too. This problem just started with the upgrade to 3.7)

**Comment by mmikkel** [comment] 2021-08-03 20:41
@adrienne I’m unable to reproduce this. Could you share the Twig code being rendered in your Preparse field(s)?

**Comment by jalendport** [comment] 2021-08-03 21:49
I'd be curious to know too what version of Craft 3.7 you're on - looks like there was a [somewhat similar bug](https://github.com/craftcms/cms/issues/9601) that got fixed in Craft 3.7.4...

**Comment by adrienne** [comment] 2021-08-03 21:54
@jalendport i'm on 3.7.7.

@mmikkel here's the code (`matrixLede` is the matrix field that won't edit properly when the preparse field is attached to the entry.)

```
{% spaceless %}
{% set seoblock = (element.matrixLede|length > 0) ? element.matrixLede.type(['blockExternalImage', 'blockImage', 'blockVideo']).one() %}
{% if seoblock|length > 0 %}
{% if seoblock.type == 'blockExternalImage' %}{{ seoblock.itemURL }}
{% elseif seoblock.type == 'blockImage' %}{% set item = blockImage.itemAsset.one() %}{{ item.url }}
{% elseif seoblock.type == 'blockVideo' %}{% set item = seoblock.itemVideoEmbed.media %}{% if item and item|length > 0 %}{{ item.image }}{% endif %}
{% endif %}
{% endif %}
```

**Comment by adrienne** [comment] 2021-08-03 21:55
Oh, also, @mmikkel - i normally keep them set to "after save", but i tried this one both ways and it makes no difference to the outcome.

As i said, it's a weird bug and if you need me to i can record some footage or hop on a call or whatever.

**Comment by mmikkel** [comment] 2021-08-04 07:22
@adrienne Thanks for sharing the Twig. I haven’t had the time to test it yet, but I suspect this isn’t actually an issue with Preparse, and that you’re running into a common element query gotcha.

Can you try to wrap all the references to `element.matrixLede` in the `clone()` function? I.e.

`element.matrixLede.type(['blockExternalImage', 'blockImage', 'blockVideo']).one()`

becomes

`clone(element.matrixLede).type(['blockExternalImage', 'blockImage', 'blockVideo']).one()`

Based on the Matrix query I’d leave the “Parse before save” setting disabled.

Let us know if this has any effect at all!

**Comment by mmikkel** [comment] 2021-08-04 11:33
@adrienne I've tested the Twig code you shared now (I created a Matrix field w/ the block types and fields referenced in the snippet, as well as a Preparse field) and I'm still unable to reproduce the issue. There is a missing `{% endspaceless %}` tag in the Twig code, but I assume that was just a copy/paste mistake – regardless I don't see the behaviour described at all.

I'd still be interested to learn if wrapping the element queries in `clone()` fixes the issue on your end. 

Beyond that, you should check your `web.log` files (in `/storage/logs`) for any Preparse related errors (do a text search for `[error][besteadfast\preparsefield`).

**Comment by adrienne** [comment] 2021-08-04 15:59
@mmikkel - D'oh, CLONING, i knew that and forgot. That seems to have fixed the problem, yes.

**Comment by mmikkel** [comment] 2021-08-04 16:06
@adrienne Great! Yeah, that’s a very common gotcha that can manifest in all sorts of issues. My guess is that due to the `type` parameter here, Craft had trouble relating all the Matrix blocks to the entry after saving it (even if I couldn’t reproduce).

@jalendport Closing this as it doesn’t appear to be an issue with Preparse.

**Closed by mmikkel** 2021-08-04 16:06 UTC
